quiet: true
soft-fail: true
download-external-modules: true
output: sarif
framework:
  - terraform
skip-check:
  - CKV_AWS_21
  - CKV_AWS_52
  - CKV_AWS_18
  - CKV_AWS_145
  - CKV_AWS_117
  - CKV2_AWS_5
  - CKV2_AWS_62
  - CKV2_AWS_64
  - CKV_AWS_144